import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "../styles/mystyle.module.css";
import React from "react";
import fs from "fs";
import {config} from "../constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface NavItemProps {
  name: string;
  href: string;
  icon: React.ReactNode;
  active?: boolean;
}

const NavItem: React.FC<NavItemProps> = ({ name, href, icon, active = false }) => {
  return (
    <a
      href={href}
      className={`nav-item 
        ${active ? "active" : ""}
        ${styles.navItem}`}
    >
      {icon}
      <span>{name}</span>
    </a>
  );
};

interface NavBarProps {
  items: NavItemProps[];
}
function MakeNavBar():NavItemProps[] {
  const getItems = (dir:string) => {
    const items = fs.readdirSync(dir).map((file) => {
      
      const name = file.replace(/\.tsx$/, "");
      const href = `/${name}`;
      const icon = <span></span>; // Placeholder for icon
      return { name, href, icon };
    });
    return items;
  }
  return getItems(config.rootdir);
}
const NavBar: React.FC<NavBarProps> = ({ items }) => {
  return (
    <nav className={styles.navBar}>
      {items.map((item, index) => (
        <NavItem key={index} {...item} />
      ))}
    </nav>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavBar items={MakeNavBar()}/>
        {children}
      </body>
    </html>
  );
}